import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import {Viewport} from "next";
import {Providers} from "@/provider";
import {Sidebar} from "@/app/screeens/layout/layout";
import { AuthProvider } from '@/app/context/AuthContext'
import { Navigation } from "./components/Navigation";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export const viewport: Viewport = {
  themeColor: '#0E0B18',
  colorScheme: 'dark',
}


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-black text-white`}
      >
         <AuthProvider>
        <Providers>
          
        {/* <Navigation /> */}
         
            <Sidebar />
            {children}
        </Providers>
        </AuthProvider>

      </body>
    </html>
  );
}
